% save_data_crop.fcn saves cropped data in indivual .mat files with
% filenames corresponding to the maneuver_label generated by the
% crop_flight_test_data.fcn. 
%
% save_data_crop(test_data, maneuver_label, i_FMUR_se, i_n580_raw_se, i_n580_filt_se, cal, altimeter, temperature)
% 
% INPUTS: 
%   test_data: data strcture from read_flight_test_data.fcn
%   maneuver_label: string vector of maneuver labels.
%   i_FMUR_se: matrix of cropping indicies for the FMUR data. 
%       The first column corresponds to the starting index, the second 
%       column corresponds to the ending index. The rows correspond to a 
%       particular maneuver.
%   i_n580_raw_se: row of starting and ending index of corresponding to the
%                   raw n580 data.
%   i_n580_filt_se: row of starting and ending index corresponding to the
%                   filtered n580 data.
%   cal: data structure of calibrations for the flight vehicle
%   altimeter: altimeter setting for the day (in Hg)
%   temperature: ambient temperature for flight test (F)
%
% OUTPUTS: (none) 
%   saves a .mat file with the "maneuver_label" filename with the following
%   variables...
%       data_FMUR -> output from process_FMUR_data.fcn
%       data_n580 -> output from process_n580_data.fcn
%       data_int -> combine_n580_FMUR_data
% 
% Sam Jaeger
% jaege246@umn.edu
% 7/8/2026

function save_data_crop(test_data, maneuver_label, i_FMUR_se, i_n580_raw_se, i_n580_filt_se, cal, altimeter, temperature)
    
    for ii=1:length(maneuver_label)
        data_FMUR = process_FMUR_data(test_data, i_FMUR_se(ii,:), cal, altimeter, temperature);
        data_n580 = process_n580_data(test_data, [],[],i_n580_raw_se(ii,:),i_n580_filt_se(ii,:));
        data_int = combine_n580_FMUR_data(data_FMUR,data_n580);

        save(string(maneuver_label(ii)), 'data_FMUR','data_n580','data_int')
    end

end